# Generated by Django 4.0 on 2021-12-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
